server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: message-service
          uri: http://localhost:8081 # 路由的目标服务，lb代表负载均衡，会从注册中心拉取服务列表,uri也可以直接写地址
          predicates:
            - Path=/message/**
          filters:
            - StripPrefix=1
          metadata:
            response-timeout: 200
            connect-timeout: 200
        - id: customer-service
          uri: http://localhost:8082
          predicates:
              - Path=/customer/**
          filters:
              - StripPrefix=1
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG


